# Generated by Django 2.2.6 on 2019-10-13 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('writtenaudio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiceprofile',
            name='TTSService',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writtenaudio.TTSService'),
        ),
    ]
