# Generated by Django 2.2.6 on 2019-10-17 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writtenaudio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tracktext',
            options={'ordering': ['time_marker', 'track'], 'verbose_name': 'Track Text'},
        ),
        migrations.AlterModelOptions(
            name='ttsservice',
            options={'ordering': ['name'], 'verbose_name': 'TTS Service'},
        ),
    ]
