# Generated by Django 2.2.6 on 2019-10-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writtenaudio', '0002_auto_20191017_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracktext',
            name='audio_file',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='tracktext',
            name='duration',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
