# Generated by Django 2.2.6 on 2019-10-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writtenaudio', '0002_track_tracktext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
