# Generated by Django 2.2.6 on 2019-10-14 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writtenaudio', '0002_auto_20191013_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['updated_at']},
        ),
    ]
