# Generated by Django 2.2.6 on 2019-10-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writtenaudio', '0003_auto_20191013_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracktext',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tracktext',
            name='text',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='tracktext',
            name='time_marker',
            field=models.IntegerField(default=0),
        ),
    ]
