# Generated by Django 2.2.6 on 2019-10-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writtenaudio', '0003_auto_20191020_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracktext',
            name='mark_for_deletion',
            field=models.BooleanField(default=False),
        ),
    ]
