# Generated by Django 2.2.6 on 2019-10-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writtenaudio', '0003_auto_20191014_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='output_format',
            field=models.CharField(choices=[('MP3', 'MP3'), ('WAV', 'WAV')], default='WAV', max_length=10),
        ),
    ]
