# Generated by Django 2.2.6 on 2019-10-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writtenaudio', '0004_track_output_format'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterField(
            model_name='tracktext',
            name='duration',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
