# Generated by Django 2.2.6 on 2019-10-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writtenaudio', '0004_tracktext_mark_for_deletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttsservice',
            name='premium_voice',
            field=models.BooleanField(default=True),
        ),
    ]
