# Generated by Django 2.2.6 on 2019-10-13 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('writtenaudio', '0005_auto_20191013_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTSChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='tracktext',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='writtenaudio.Track'),
        ),
        migrations.AddField(
            model_name='tracktext',
            name='tts_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='writtenaudio.TTSChoice'),
        ),
    ]
