# Generated by Django 2.2.6 on 2019-10-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writtenaudio', '0005_auto_20191015_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiceprofile',
            name='TTSService',
        ),
        migrations.RemoveField(
            model_name='voiceprofile',
            name='profile_name',
        ),
        migrations.RemoveField(
            model_name='voiceprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='ttsservice',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
