# Generated by Django 2.2.6 on 2019-10-13 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writtenaudio', '0006_auto_20191013_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tracktext',
            options={'ordering': ['time_marker', 'track']},
        ),
    ]
