# Generated by Django 2.2.6 on 2019-10-21 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writtenaudio', '0007_ttsservice_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ttsservice',
            old_name='default',
            new_name='system_default_profile',
        ),
    ]
