# Generated by Django 2.2.6 on 2019-10-17 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writtenaudio', '0007_auto_20191017_0828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ttsservice',
            options={'ordering': ['name']},
        ),
    ]
