# Generated by Django 2.2.6 on 2019-10-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writtenaudio', '0008_auto_20191017_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttsservice',
            name='language_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
