# Generated by Django 2.2.6 on 2019-10-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writtenaudio', '0008_auto_20191021_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracktext',
            name='audio_file_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
