# Generated by Django 2.2.6 on 2019-10-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writtenaudio', '0009_tracktext_audio_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='file_url',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
