# Generated by Django 2.2.6 on 2019-10-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writtenaudio', '0012_uservoiceprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttsservice',
            name='avatar_image_path',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='ttsservice',
            name='sample_audio_path',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='ttsservice',
            name='voice_profile_description',
            field=models.CharField(default='', max_length=300),
        ),
    ]
