# Generated by Django 2.2.6 on 2019-10-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writtenaudio', '0013_auto_20191027_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttsservice',
            name='avatar_image_path',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='ttsservice',
            name='sample_audio_path',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='ttsservice',
            name='voice_profile_description',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
