# Generated by Django 2.2.6 on 2019-10-31 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writtenaudio', '0015_auto_20191029_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='audio_speed',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
