# Generated by Django 2.2.6 on 2019-11-17 10:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('writtenaudio', '0018_track_audio_pitch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language_code', models.CharField(max_length=10)),
            ],
        ),
    ]
