# Generated by Django 2.2.6 on 2019-11-17 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('writtenaudio', '0019_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='language_display',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='writtenaudio.Language'),
        ),
        migrations.AddField(
            model_name='track',
            name='parent_track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='writtenaudio.Track'),
        ),
    ]
