# Generated by Django 2.2.6 on 2019-11-17 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writtenaudio', '0020_auto_20191117_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='language_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='language_display',
            new_name='display_name',
        ),
    ]
