# Generated by Django 2.2.6 on 2019-11-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writtenaudio', '0021_auto_20191117_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='display_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
