# Generated by Django 2.2.6 on 2019-11-17 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('writtenaudio', '0022_auto_20191117_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracktext',
            name='editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tracktext',
            name='parent_track_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='writtenaudio.TrackText'),
        ),
    ]
