# Generated by Django 2.2.6 on 2019-11-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writtenaudio', '0023_auto_20191117_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
