# Generated by Django 2.2.6 on 2019-11-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writtenaudio', '0024_language_enabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['-display_name']},
        ),
        migrations.RemoveField(
            model_name='track',
            name='parent_track',
        ),
        migrations.AddField(
            model_name='track',
            name='cloned',
            field=models.BooleanField(default=False),
        ),
    ]
