# Generated by Django 2.2.6 on 2019-12-03 12:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('writtenaudio', '0027_language_system_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicTrack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('genre', models.CharField(blank=True, max_length=40, null=True)),
                ('track_name', models.CharField(blank=True, max_length=40, null=True)),
                ('enabled', models.BooleanField(default=False)),
                ('filename', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'ordering': ['track_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['display_name']},
        ),
    ]
