# Generated by Django 2.2.6 on 2019-12-03 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('writtenaudio', '0028_auto_20191203_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='musictrack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='writtenaudio.MusicTrack'),
        ),
    ]
